server:
  port: 8080
spring:
  application:
    name: birthdayreminder
  data:
    redis:
      timeout: 5000
      lettuce:
        shutdown-timeout: 100ms
      ssl:
        enabled: true


redis:
  url: free-corgi-27372.upstash.io
  port: 6379
  password: AWrsAAIjcDE1OGY4NGI0ZjIxZDI0ODlmYWQ3NzA0ZmViYjEyOTJiM3AxMA
