server:
  port: 8080
spring:
  application:
    name: birthdayreminder
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration


redis:
  url: free-corgi-27372.upstash.io
  port: 6379
  password: AWrsAAIjcDE1OGY4NGI0ZjIxZDI0ODlmYWQ3NzA0ZmViYjEyOTJiM3AxMA